name: golangci-lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          only-new-issues: true
